server:
  port: ${static.diyPort}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tuan?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 51MB

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yaxin.tuanbs.entity
  configuration:
    cache-enabled: true

#showSql
logging:
  level:
    com:
      yaxin:
        regionsensebs:
          mapper: debug
  file:
    name: tuan.log
  logback:
    rollingpolicy:
      max-history: 2
      clean-history-on-start: true


#分页框架
#pagehelper:
#  auto-dialect: true #自动适配SQL（我们使用的是mysql）
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
static:
  diyPort: 9001
  profile: E:/IDEA_project/tuanstatic
  rootURL: http://172.17.23.203:${static.diyPort}/profile
  maxImageSize: 10485760 #10MB
  folders:
    pics: pics
  Record:
    PageSize: 10
